"""empty message

Revision ID: eca981659596
Revises: 
Create Date: 2019-10-06 19:18:26.326499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eca981659596'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=False),
    sa.Column('transaction_amount', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=False),
    sa.Column('transaction_time', mysql.DECIMAL(precision=20, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
